### PR TITLE
Allowing for Optional build-id Input

### PR DESCRIPTION
**Pull request by willmarks**
## Description

In order to ensure backward compatibility the code will continue to pull the `build-id` from the GITHUB_RUN_ID unless an override is manually passed into the action via the `build-id` input param.

## Things I need to figure out

What is the best way to test a GH action?

## Type of change
- [ ] Bug fix
- [X] New feature
- [ ] Breaking change

## Related issues

https://github.com/faros-ai/tickets/issues/198

## Related PR

https://github.com/faros-ai/poseidon/pull/1274

### CODE REVIEW

**Comment by tovbinm** [comment]
@willmarks you can add test it locally with [act](https://github.com/nektos/act). Also modify the test workflow https://github.com/faros-ai/faros-cicd-github-action/blob/main/.github/workflows/test.yml and expose the new variable in https://github.com/faros-ai/faros-cicd-github-action/blob/main/action.yml

**Comment by chalenge** [comment]
> @willmarks you can add test it locally with [act](https://github.com/nektos/act). Also modify the test workflow https://github.com/faros-ai/faros-cicd-github-action/blob/main/.github/workflows/test.yml and expose the new variable in https://github.com/faros-ai/faros-cicd-github-action/blob/main/action.yml

@willmarks Last time I tried, act didn't work with local github action but you can try. Another option is to enable these tests locally https://github.com/faros-ai/faros-cicd-github-action/blob/main/__tests__/main.test.ts#L168

**Comment by willmarks** [comment]
Let me know if we want this functionality for another purpose because the reason that I made it no longer applies given my most recent change to https://github.com/faros-ai/poseidon/pull/1274. If we don't need this anymore then I can just close this PR.

**Comment by tovbinm** [comment]
Yeah, let's close it. the simpler the better.

**Pull request closed without merging**
