### PR TITLE
Allow sending details for run status, deploy status and env

### PR DESCRIPTION
**Pull request by tovbinm**
## Description

Allow sending details for run status, deploy status and env

## Type of change
- [ ] Bug fix
- [x] New feature
- [ ] Breaking change

### CODE REVIEW

**Review by willmarks — APPROVED** [review]
lgtm!

**Review by willmarks — CHANGES_REQUESTED** [review]
Forgot one thing

**Comment by tovbinm** [comment]
@willmarks what did we forget?

**Comment by willmarks** [comment]
We need to package it and then attach the new dist files as those are what are used by the GHA.

**Review by willmarks — APPROVED** [review]

**Pull request merged**
